### ISSUE TITLE
Update Rating seed to match GRP

### ISSUE THREAD

**Issue by mkosmo** [ZHU-ARTCC/artccmgr#12]
In artccmgr/db/seeds.rb, update names to match GRP ratings.  C2/I2 will remain as-is since there are no GRP names for the ratings.

https://www.vatsim.net/documents/global-ratings-policy

**Comment by jvoss** [comment]
While you're at it, add a column for the rating integer as fed from VATSIM. 

Currently the table only collects the name and short_name but integer value would be good to have as well for training sequencing if nothing else.

**Comment by mkosmo** [comment]
We can also probably find a reason to use it when collecting VATSIM stats.
